### ISSUE TITLE
django.db.utils.OperationalError: no such table: django_site

### ISSUE THREAD

**Issue by zer-far** [HermanMartinus/bearblog#202]
Running `SECRET=SECRET DEBUG=False python3 manage.py makemigrations` and `SECRET=SECRET DEBUG=False python3 manage.py migrate` both produce the same error below.

```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_site

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/Desktop/bearblog/manage.py", line 21, in <module>
    main()
  File "/home/user/Desktop/bearblog/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/urls/resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/urls/resolvers.py", line 593, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/urls/resolvers.py", line 586, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/user/Desktop/bearblog/textblog/urls.py", line 9, in <module>
    path('', include('blogs.urls')),
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/user/Desktop/bearblog/blogs/urls.py", line 4, in <module>
    from .views import blog, dashboard, studio, feed, discover, analytics, emailer, staff
  File "/home/user/Desktop/bearblog/blogs/views/blog.py", line 23, in <module>
    from blogs.views.studio import render_analytics
  File "/home/user/Desktop/bearblog/blogs/views/studio.py", line 22, in <module>
    from blogs.forms import AnalyticsForm, PostTemplateForm
  File "/home/user/Desktop/bearblog/blogs/forms.py", line 149, in <module>
    class PostForm(forms.ModelForm):
  File "/home/user/Desktop/bearblog/blogs/forms.py", line 201, in PostForm
    help_text=f"Show in the <a href='https://{root()}/discover/' target='_blank'>discovery feed</a>",
  File "/home/user/Desktop/bearblog/blogs/helpers.py", line 18, in root
    domain = Site.objects.get_current().domain
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/contrib/sites/models.py", line 58, in get_current
    return self._get_site_by_id(site_id)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/user/.pyenv/versions/3.9.13/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_site
```

**Comment by HermanMartinus** [comment]
When making your migration for the first time, comment out all instances of `Site.object.all()` then uncomment them to run migrate. 

This seems to be a quirk of the `contrib.sites.models` lib.
